const data = [
    {
        id: 1,
        title: "Helpful Tips for Working from Home as a Freelancer",
        excerpt: "Embrace the boundless realm of creativity, tapping into your artistic spirit to express yourself freely and unlock untapped potential",
        img: "img1.jpg",
        category: "Working Tips",
        author: "author.jpg",
        date: "25 April 2023",
    },
    {
        id: 2,
        title: "10 Easy Ways to Be Environmentally Conscious At Home",
        excerpt: "Embark on a profound quest for inner serenity through mindfulness practices, fostering a sense of peace and balance in your daily life",
        img: "img6.jpg",
        category: "Development",
        author: "author.jpg",
        date: "25 April 2023",
    },
    {
        id: 3,
        title: "How to Give Your Space a Parisian-Inspired Makeover",
        excerpt: "Navigate the transformative journey of personal growth, as you adapt to life's changes and emerge stronger, ready to embrace new possibilities",
        img: "img3.jpg",
        category: "Lifestyle",
        author: "author.jpg",
        date: "25 April 2023",
    },
    {
        id: 4,
        title: "Facts About Business That Will Help You Success",
        excerpt: "Immerse yourself in the beauty of the natural world, as you learn to connect with and appreciate nature's wonders through these enlightening tips",
        img: "img4.jpg",
        category: "Business",
        author: "author.jpg",
        date: "25 April 2023",
    },
    {
        id: 5,
        title: "The Next 60 Things To Immediately Do About Building A Plan",
        excerpt: "Dive into the realm of planning and strategic thinking, as you lay the groundwork for a dynamic and effective roadmap to achieve your aspirations",
        img: "img5.jpg",
        category: "Building",
        author: "author.jpg",
        date: "25 April 2023",
    },
    {
        id: 6,
        title: "Master The Art Of Nature With These 7 Tips",
        excerpt: "Equip yourself with essential business insights and proven strategies that can propel your career towards unparalleled success and growth",
        img: "img6.jpg",
        category: "Joseph",
        author: "author.jpg",
        date: "25 April 2023",
    },
    {
        id: 7,
        title: "Your Light Is About To Stop Being Relevant",
        excerpt: "Infuse the timeless elegance of Parisian aesthetics into your living space with expert design guidance, creating an inviting atmosphere that exudes sophistication",
        img: "img7.jpg",
        category: "Joseph",
        author: "author.jpg",
        date: "25 April 2023",
    },
    {
        id: 8,
        title: "Your Light Is About To Stop Being Relevant",
        excerpt: "Take small but impactful steps towards environmental stewardship and sustainability within the comfort of your own home, contributing to a greener planet",
        img: "img8.jpg",
        category: "Joseph",
        author: "author.jpg",
        date: "25 April 2023",
    },
    {
        id: 9,
        title: "Master The Art Of Nature With These 7 Tips",
        excerpt: "Embrace remote work success with these invaluable tips and tricks for freelancers seeking productivity and work-life balance in their home offices",
        img: "img9.jpg",
        category: "Joseph",
        author: "author.jpg",
        date: "25 April 2023",
    }
];
export default data;