const data = [
    {
        id: 1,
        title: "Are You Ready To Go Home After The Sunset View?",
        excerpt: "Gosh jaguar ostrich quail one excited dear hello and bound and the and bland moral misheard roadrunner flapped lynx far that and jeepers giggled far and far",
        img: "news1.png",
        authorTitle: "Joseph",
        author: "author.jpg",
        date: "25 April 2023",
    },
    {
        id: 2,
        title: "Life is as free as eagles, or is it just loneliness?",
        excerpt: "Exploring the Wonders of Artificial Intelligence: From self-learning algorithms to intelligent automation, delve into AI's transformative impact on diverse industries",
        img: "news2.png",
        authorTitle: "Joseph",
        author: "author.jpg",
        date: "25 April 2023",
    },
    {
        id: 3,
        title: "16 Unheard Ways To Achieve Greater Walker",
        excerpt: "Virtual Reality: Beyond Imagination: Step into immersive worlds, where virtual reality blurs the line between the real and the unreal, opening new possibilities",
        img: "news3.png",
        authorTitle: "Joseph",
        author: "author.jpg",
        date: "25 April 2023",
    },
    {
        id: 4,
        title: "Master The Art Of Nature With These 7 Tips",
        excerpt: "Blockchain Unveiled: Decentralizing Trust: Unravel the potential of blockchain as it revolutionizes finance, supply chains, and digital security.",
        img: "news4.png",
        authorTitle: "Joseph",
        author: "author.jpg",
        date: "25 April 2023",
    },
    {
        id: 5,
        title: "16 Unheard Ways To Achieve Greater Walker",
        excerpt: "The Era of 5G: Powering Connectivity: Discover how 5G technology is reshaping communication, unlocking lightning-fast connectivity",
        img: "news5.png",
        authorTitle: "Joseph",
        author: "author.jpg",
        date: "25 April 2023",
    },
    {
        id: 6,
        title: "Master The Art Of Nature With These 7 Tips",
        excerpt: "Quantum Computing: Pioneering the Unseen: Venture into the realm of quantum computing, where qubits defy classical computing boundaries",
        img: "news6.png",
        authorTitle: "Joseph",
        author: "author.jpg",
        date: "25 April 2023",
    },
    {
        id: 7,
        title: "Your Light Is About To Stop Being Relevant",
        excerpt: "Internet of Things: A Connected Universe: Witness the IoT's expansive network, interlinking smart devices and reshaping everyday living",
        img: "news7.png",
        authorTitle: "Joseph",
        author: "author.jpg",
        date: "25 April 2023",
    },
    {
        id: 8,
        title: "Your Light Is About To Stop Being Relevant",
        excerpt: "Machine Learning: The Art of Intelligent Insights: Journey through the world of machine learning, empowering data-driven decision-making",
        img: "news8.png",
        authorTitle: "Joseph",
        author: "author.jpg",
        date: "25 April 2023",
    },
    {
        id: 9,
        title: "Master The Art Of Nature With These 7 Tips",
        excerpt: "Cybersecurity: Fortifying the Digital Realm: Safeguarding sensitive data and privacy amidst the ever-evolving cyber threats",
        img: "news9.png",
        authorTitle: "Joseph",
        author: "author.jpg",
        date: "25 April 2023",
    }
];

export default data;