const categories = [
    {
        id: 1,
        title: "Travel",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
        img: "tag1.png",
        imgBig: "cat1.png",
        postCount: "36",
        url: "travel",
    },
    {
        id: 2,
        title: "Culture",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
        img: "tag2.png",
        imgBig: "cat2.png",
        postCount: "18",
        url: "",
    },
    {
        id: 3,
        title: "Lifestyle",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
        img: "tag3.png",
        imgBig: "cat3.png",
        postCount: "44",
        url: "",
    },
    {
        id: 4,
        title: "Fashion",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
        img: "tag4.png",
        imgBig: "cat4.png",
        postCount: "65",
        url: "",
    },
    {
        id: 5,
        title: "Food",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
        img: "tag5.png",
        imgBig: "cat5.png",
        postCount: "37",
        url: "",
    },
    {
        id: 6,
        title: "Space",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
        img: "tag6.png",
        imgBig: "cat6.png",
        postCount: "27",
        url: "",
    },
    {
        id: 7,
        title: "Animal",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
        img: "tag7.png",
        imgBig: "cat7.png",
        postCount: "16",
        url: "",
    },
    {
        id: 8,
        title: "Minimal",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
        img: "tag8.png",
        imgBig: "cat8.png",
        postCount: "87",
        url: "",
    },
    {
        id: 9,
        title: "Interior",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
        img: "tag9.png",
        imgBig: "cat9.png",
        postCount: "27",
        url: "",
    },
    {
        id: 10,
        title: "Plant",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
        img: "tag10.png",
        imgBig: "cat10.png",
        postCount: "25",
        url: "",
    },
    {
        id: 11,
        title: "Nature",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
        img: "tag11.png",
        imgBig: "cat11.png",
        postCount: "43",
        url: "",
    },
    {
        id: 12,
        title: "Business",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
        img: "tag12.png",
        imgBig: "cat12.png",
        postCount: "45",
        url: "",
    },
];

export default categories;